sudo: false
language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install:
  - composer install -o --prefer-dist --no-interaction

script:
    - if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs -p -s -v -n . --standard=./codesniffer.ruleset.xml --extensions=php; fi
